name: poup_app
description: Projeto Integrador - Aplicativo Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones incríveis (menu, setas, etc.)
  font_awesome_flutter: ^10.7.0

  # Fontes personalizadas (se quiser usar no app)
  google_fonts: ^6.1.0

  # Gráficos bonitos (linha, barras, pizza)
  fl_chart: ^0.66.2

  # Armazenamento local (guardar dados localmente)
  shared_preferences: ^2.2.2

  # Ícones estilo iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
